# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trellowebapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Set Database Password
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './src/main/resources/application.properties'
        property: 'spring.datasource.password'
        value: ${{secrets.APPLICATIONUSERPASSWORD}}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c0a99ab69cd43d8a4f08def65456df3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d58831a152f04b29812c4d5a3a679101 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6c0a99ab69cd43d8a4f08def65456df3 }}/monishkumarm/trello:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'trellowebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_75a5b9f64e7b43c4b475b32dd0749ceb }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6c0a99ab69cd43d8a4f08def65456df3 }}/monishkumarm/trello:${{ github.sha }}'
